[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/sw-push.js"
  to = "/sw-push.js"
  status = 200

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.webmanifest"
  status = 200

[[redirects]]
  from = "/workbox-*"
  to = "/workbox-:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/OneSignalSDKWorker.js"
  to = "/OneSignalSDKWorker.js"
  status = 200

[[redirects]]
  from = "/OneSignalSDKUpdaterWorker.js"
  to = "/OneSignalSDKUpdaterWorker.js"
  status = 200


[[redirects]]
  from = "/onesignal/OneSignalSDKWorker.js"
  to = "/onesignal/OneSignalSDKWorker.js"
  status = 200

[[redirects]]
  from = "/onesignal/OneSignalSDKUpdaterWorker.js"
  to = "/onesignal/OneSignalSDKUpdaterWorker.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
